package repo

import (
	"errors"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"testing"

	"github.com/donaldgifford/docz/v2/pkg/doczcore/docparse"
	"github.com/donaldgifford/docz/v2/pkg/doczcore/document"
	"github.com/donaldgifford/docz/v2/pkg/impl"
)

// The corpus proofs for the migration pass (IMPL-0018 Phase 3, task 11).
//
// InsertRegions is the one writer of region markers outside the templates, and
// the documents it will run over already exist: the five type packages each
// carry a snapshot corpus of real fleet documents paired with the marked copy a
// person reviewed, and this repository's own docs/ tree is the largest single
// body of unmarked documents docz has. Three things are proven here.
//
//  1. The pass reproduces every hand-reviewed pair byte for byte, and running
//     it twice changes nothing. The pairs were generated by the type packages'
//     own fixture writer, so agreement means the two implementations of "write
//     the spans inference found" cannot drift apart unnoticed.
//  2. The pass over docz's own corpus yields regions that read back as the
//     kinds it inserted, and a second run is a no-op.
//  3. A locator written for this test, walking headings with no help from kinds
//     or from any type package, finds the same tasks in an unmarked plan that
//     impl.Parse finds in the marked one. That is the heuristic's parity proof:
//     migration must not move a task, because a Task ID is an address and those
//     addresses are in commit messages.
//
// Nothing here edits a fixture or the real docs/ tree. A fixture that does not
// round-trip is a finding about the pass, not a fixture to regenerate.

// migrationTypePackages maps each type package's directory name to the docz
// type its documents belong to. They happen to agree for four of the five;
// pkg/investigation is spelled out rather than derived so the pair is stated
// once rather than guessed at each use.
var migrationTypePackages = map[string]string{
	"rfc":           "rfc",
	"adr":           "adr",
	"design":        "design",
	"impl":          "impl",
	"investigation": "investigation",
}

// migrationRepoRoot is this repository's root as seen from this package's
// directory: pkg/doczcore/repo is three levels down.
const migrationRepoRoot = "../../.."

// migrationFixtureDir returns a type package's testdata directory.
func migrationFixtureDir(pkgName string) string {
	return filepath.Join(migrationRepoRoot, "pkg", pkgName, "testdata")
}

// migrationOrigFixtures lists the base names of every *.orig.md in a type
// package's testdata directory.
func migrationOrigFixtures(t *testing.T, pkgName string) []string {
	t.Helper()

	entries, err := os.ReadDir(migrationFixtureDir(pkgName))
	if err != nil {
		t.Fatalf("reading %s: %v", migrationFixtureDir(pkgName), err)
	}

	var names []string

	for _, entry := range entries {
		if name, ok := strings.CutSuffix(entry.Name(), ".orig.md"); ok {
			names = append(names, name)
		}
	}

	if len(names) == 0 {
		t.Fatalf("no *.orig.md fixtures under %s", migrationFixtureDir(pkgName))
	}

	slices.Sort(names)

	return names
}

// migrationReadFixture reads one file out of a type package's testdata
// directory.
func migrationReadFixture(t *testing.T, pkgName, filename string) []byte {
	t.Helper()

	b, err := os.ReadFile(filepath.Join(migrationFixtureDir(pkgName), filename))
	if err != nil {
		t.Fatalf("reading fixture %s: %v", filename, err)
	}

	return b
}

// migrationMigrate writes one document into a fresh repository, runs the pass
// over its type, and returns the report and the resulting bytes.
//
// The filename is synthesized rather than taken from the fixture because
// document.ScanDocuments only sees files matching the docz convention, and a
// fixture is named after where it came from.
func migrationMigrate(
	t *testing.T, typeName string, body []byte,
) (InsertRegionsReport, []byte, *Repo, string) {
	t.Helper()

	r := regionsFixtureRepo(t)
	path := regionsPutDoc(t, r, typeName, "0001-fixture.md", string(body))

	report, err := r.InsertRegions(t.Context(), []string{typeName}, InsertRegionsOptions{})
	if err != nil {
		t.Fatalf("InsertRegions over %s: %v", typeName, err)
	}

	out, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading migrated document: %v", err)
	}

	return report, out, r, path
}

// migrationAssertSecondRunIsNoOp reruns the pass and fails if it touches
// anything.
//
// Idempotence is a design property rather than a nicety: a repo runs
// `docz validate --fix` once, reviews the diff, and commits, and a pass that
// kept finding work would make that review never end.
func migrationAssertSecondRunIsNoOp(t *testing.T, r *Repo, typeName, path string, first []byte) {
	t.Helper()

	report, err := r.InsertRegions(t.Context(), []string{typeName}, InsertRegionsOptions{})
	if err != nil {
		t.Fatalf("second InsertRegions over %s: %v", typeName, err)
	}

	if len(report.Changed) != 0 {
		t.Errorf("second run changed %v, want nothing", report.Changed)
	}

	again, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading document after the second run: %v", err)
	}

	if !slices.Equal(again, first) {
		t.Errorf("second run rewrote the document:\n%s", migrationFirstDifference(string(again), string(first)))
	}
}

// migrationFirstDifference names the first line two documents disagree on,
// because a diff of two 500-line documents is unreadable in test output and
// the first difference is nearly always the whole story.
func migrationFirstDifference(got, want string) string {
	gotLines := strings.Split(got, "\n")
	wantLines := strings.Split(want, "\n")

	for i := 0; i < len(gotLines) && i < len(wantLines); i++ {
		if gotLines[i] != wantLines[i] {
			return "line " + strconv.Itoa(i+1) + ":\n got: " + strconv.Quote(gotLines[i]) +
				"\nwant: " + strconv.Quote(wantLines[i])
		}
	}

	if len(gotLines) != len(wantLines) {
		return "line counts differ: got " + strconv.Itoa(len(gotLines)) +
			", want " + strconv.Itoa(len(wantLines))
	}

	return "documents are equal"
}

// TestMigrationFixtureEquality is proof 1: the pass reproduces every
// hand-reviewed pair in the five type packages byte for byte.
//
// The .md sibling of each .orig.md is the spans inference found, written out as
// markers and nothing else: no heading added, no prose moved, no blank line
// inserted. Those files were produced by the type packages' own fixture writer,
// which is a second implementation of the same rule, so equality here is the
// only thing keeping the two from drifting.
func TestMigrationFixtureEquality(t *testing.T) {
	t.Parallel()

	for pkgName, typeName := range migrationTypePackages {
		t.Run(pkgName, func(t *testing.T) {
			t.Parallel()

			for _, name := range migrationOrigFixtures(t, pkgName) {
				t.Run(name, func(t *testing.T) {
					t.Parallel()

					orig := migrationReadFixture(t, pkgName, name+".orig.md")
					want := migrationReadFixture(t, pkgName, name+".md")

					report, got, r, path := migrationMigrate(t, typeName, orig)

					if !slices.Equal(got, want) {
						t.Errorf("migrated %s/%s does not match its reviewed sibling:\n%s",
							pkgName, name, migrationFirstDifference(string(got), string(want)))
					}

					if len(report.Changed) != 1 {
						t.Errorf("report Changed = %v, want exactly one entry", report.Changed)
					}

					migrationAssertSecondRunIsNoOp(t, r, typeName, path, got)
				})
			}
		})
	}
}

// migrationCorpusTypes are the type directories under docs/ that carry
// documents. docs/rfc and docs/plan are omitted because this repository has
// none, and a subtest that scanned an empty directory would pass without
// proving anything.
var migrationCorpusTypes = []string{"adr", "design", "impl", "investigation"}

// migrationMarkerLine matches a whole region-marker line including its
// newline, so removing one leaves the document's own lines untouched.
var migrationMarkerLine = regexp.MustCompile(
	`(?m)^[ \t]*<!--docz:[a-z0-9-]+:(?:start|end)-->\n`,
)

// migrationSnapshotCorpus copies this repository's own documents into a fresh
// repository, with their region markers taken back out, and returns it.
//
// A copy rather than a run in place. The pass writes, and a test that wrote to
// docs/ would rewrite the documents it is reading its expectations from — and
// would do it the first time somebody ran the suite, before anybody had
// reviewed a diff.
//
// The strip is what keeps this a migration. IMPL-0018 Phase 5 ran the pass over
// docs/ for real, so copying the corpus verbatim now hands the fixer documents
// it has already fixed and the proof degenerates into the no-op case — which
// the idempotence half of this test covers anyway, on its second run.
func migrationSnapshotCorpus(t *testing.T) *Repo {
	t.Helper()

	r := regionsFixtureRepo(t)

	for _, typeName := range migrationCorpusTypes {
		src := filepath.Join(migrationRepoRoot, "docs", typeName)

		entries, err := os.ReadDir(src)
		if err != nil {
			t.Fatalf("reading %s: %v", src, err)
		}

		copied := 0

		for _, entry := range entries {
			if entry.IsDir() || !document.IsDoczFile(entry.Name()) {
				continue
			}

			body, err := os.ReadFile(filepath.Join(src, entry.Name()))
			if err != nil {
				t.Fatalf("reading %s: %v", entry.Name(), err)
			}

			bare := migrationMarkerLine.ReplaceAllString(string(body), "")

			regionsPutDoc(t, r, typeName, entry.Name(), bare)

			copied++
		}

		if copied == 0 {
			t.Fatalf("no documents copied out of %s", src)
		}
	}

	return r
}

// TestMigrationOwnCorpus is proof 2: the pass over docz's own documents yields
// regions that read back as exactly the kinds it inserted, every kind is one
// the type's spec declares, and a second run changes nothing.
//
// The assertion is stated against the walker rather than against a list of
// expected kinds per document. A list would have to be edited every time
// somebody wrote a doc, and a test somebody edits to make it pass has stopped
// testing anything.
func TestMigrationOwnCorpus(t *testing.T) {
	t.Parallel()

	r := migrationSnapshotCorpus(t)

	report, err := r.InsertRegions(t.Context(), migrationCorpusTypes, InsertRegionsOptions{})
	if err != nil {
		t.Fatalf("InsertRegions over the corpus: %v", err)
	}

	if len(report.Changed) == 0 {
		t.Fatal("the corpus produced no changed documents; the pass did nothing")
	}

	before := make(map[string][]byte, len(report.Changed))

	for i := range report.Changed {
		result := report.Changed[i]

		path := filepath.Join(r.Root, result.Path)

		got, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("reading %s: %v", result.Path, err)
		}

		before[result.Path] = got

		migrationCheckRegions(t, r, &result, got)
	}

	second, err := r.InsertRegions(t.Context(), migrationCorpusTypes, InsertRegionsOptions{})
	if err != nil {
		t.Fatalf("second InsertRegions over the corpus: %v", err)
	}

	if len(second.Changed) != 0 {
		t.Errorf("second run changed %d documents, want none", len(second.Changed))
	}

	for rel, want := range before {
		got, err := os.ReadFile(filepath.Join(r.Root, rel))
		if err != nil {
			t.Fatalf("reading %s after the second run: %v", rel, err)
		}

		if !slices.Equal(got, want) {
			t.Errorf("%s changed on the second run:\n%s",
				rel, migrationFirstDifference(string(got), string(want)))
		}
	}
}

// migrationCheckRegions asserts that one migrated document's regions are the
// ones the report says were inserted, and that every kind is one the type's
// own spec declares.
func migrationCheckRegions(t *testing.T, r *Repo, result *InsertRegionsResult, doc []byte) {
	t.Helper()

	got := doczRegions(doc)

	kindsGot := make([]string, 0, len(got))

	for i := range got {
		if !got[i].Closed {
			t.Errorf("%s: %s region at line %d is unclosed", result.Path, got[i].Kind, got[i].Start)
		}

		kindsGot = append(kindsGot, got[i].Kind)
	}

	if !slices.Equal(kindsGot, result.Inserted) {
		t.Errorf("%s: regions read back as %v, want the inserted %v",
			result.Path, kindsGot, result.Inserted)
	}

	typeName := filepath.Base(filepath.Dir(result.Path))

	spec, err := r.headingSpec(typeName)
	if err != nil {
		t.Fatalf("resolving %s spec: %v", typeName, err)
	}

	declared := make(map[string]bool, len(spec))
	for i := range spec {
		declared[spec[i].Kind] = true
	}

	for _, kind := range result.Inserted {
		if !declared[kind] {
			t.Errorf("%s: inserted kind %q is not in the %s spec", result.Path, kind, typeName)
		}
	}
}

// migrationPhaseHeading is the locator's own phase-heading rule, written here
// rather than borrowed so the proof is a second opinion and not a restatement
// of the first.
//
// A token may not contain whitespace or a slash and must be followed by a
// colon, which is what keeps `### Phase 1` under a File Changes table from
// being read as a phase.
var migrationPhaseHeading = regexp.MustCompile(`(?i)^Phase\s+([^\s/:]+):`)

// migrationComment matches an HTML comment, which a template's placeholder
// phase title still is.
var migrationComment = regexp.MustCompile(`(?s)<!--.*?-->`)

// migrationTask is one task as the locator sees it: its positional ID and the
// verbatim text of its checkbox line.
//
// The line text rather than the line number, because migration inserts marker
// lines and every number below one of them moves. The text is what has to
// survive.
type migrationTask struct {
	ID   string
	Line string
}

// migrationLocateTasks finds a plan's tasks by walking its headings.
//
// Deliberately naive and deliberately independent: level-3 headings that name
// a phase token, a level-4 "Tasks" heading inside each, and the unindented
// checkbox items under that. No kinds, no spec, no type package. If this and
// impl.Parse over the migrated copy disagree, the migration moved a task.
func migrationLocateTasks(doc []byte) []migrationTask {
	lines := strings.Split(strings.TrimSuffix(string(doc), "\n"), "\n")
	heads := docparse.Headings(doc)

	var out []migrationTask

	for i := range heads {
		if heads[i].Level != 3 {
			continue
		}

		m := migrationPhaseHeading.FindStringSubmatch(migrationComment.ReplaceAllString(heads[i].Text, ""))
		if m == nil {
			continue
		}

		phaseEnd := migrationSpanEnd(heads, i, 3, len(lines))

		from, through, ok := migrationTasksSpan(heads, i, phaseEnd)
		if !ok {
			continue
		}

		out = append(out, migrationTasksIn(lines, from, through, strings.TrimSpace(m[1]))...)
	}

	return out
}

// migrationSpanEnd returns the last line of the span opened by heads[i]: the
// line before the next heading of the same or shallower level, or last.
func migrationSpanEnd(heads []docparse.Heading, i, level, last int) int {
	for _, next := range heads[i+1:] {
		if next.Level <= level {
			return next.Line - 1
		}
	}

	return last
}

// migrationTasksSpan returns the first and last line of the level-4 Tasks
// section inside the phase opened at heads[i], or false when the phase has
// none.
func migrationTasksSpan(heads []docparse.Heading, i, phaseEnd int) (from, through int, ok bool) {
	for j := i + 1; j < len(heads); j++ {
		if heads[j].Line > phaseEnd {
			break
		}

		if heads[j].Level != 4 || !strings.EqualFold(strings.TrimSpace(heads[j].Text), "Tasks") {
			continue
		}

		through = migrationSpanEnd(heads, j, 4, phaseEnd)
		if through > phaseEnd {
			through = phaseEnd
		}

		return heads[j].Line, through, true
	}

	return 0, 0, false
}

// migrationTasksIn returns the unindented checkbox items of one Tasks section,
// numbered from 1 within the phase.
func migrationTasksIn(lines []string, from, through int, token string) []migrationTask {
	if through < from {
		return nil
	}

	body := strings.Join(lines[from-1:through], "\n")

	var out []migrationTask

	index := 0

	for _, item := range docparse.TaskItems([]byte(body)) {
		if item.Indent > 0 {
			continue
		}

		index++

		out = append(out, migrationTask{
			ID:   token + "." + strconv.Itoa(index),
			Line: lines[from-1+item.Line-1],
		})
	}

	return out
}

// TestHeuristicsParityOverImplCorpus is proof 3: the heading-based locator over
// an unmarked plan finds the same tasks impl.Parse finds in the marked one.
//
// A Task ID is an address — "1.3" is in a commit message somewhere — so the one
// thing migration must not do is renumber. Comparing the checkbox line's text
// rather than its number is the point: the numbers move by exactly the markers
// inserted above them, and the text is what must not.
//
// This file imports pkg/impl, which the layer rule permits: TestLayerRules
// walks `go list -deps`, which reports production imports only, so a test may
// reach up a layer to prove the two agree. The production side of repo imports
// no type package and the same layer test enforces it.
func TestHeuristicsParityOverImplCorpus(t *testing.T) {
	t.Parallel()

	for _, name := range migrationOrigFixtures(t, "impl") {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			orig := migrationReadFixture(t, "impl", name+".orig.md")

			_, migrated, _, _ := migrationMigrate(t, "impl", orig)

			want := migrationLocateTasks(orig)

			parsed, err := impl.Parse(migrated)
			if err != nil {
				if errors.Is(err, impl.ErrNoPhases) && len(want) == 0 {
					return
				}

				t.Fatalf("impl.Parse over the migrated copy: %v", err)
			}

			lines := strings.Split(strings.TrimSuffix(string(migrated), "\n"), "\n")

			tasks := parsed.Tasks()

			got := make([]migrationTask, 0, len(tasks))

			for i := range tasks {
				if tasks[i].Line < 1 || tasks[i].Line > len(lines) {
					t.Fatalf("task %s reports line %d, outside the %d-line document",
						tasks[i].ID, tasks[i].Line, len(lines))
				}

				got = append(got, migrationTask{ID: tasks[i].ID, Line: lines[tasks[i].Line-1]})
			}

			if len(got) != len(want) {
				t.Fatalf("impl.Parse found %d tasks, the locator found %d\n got: %v\nwant: %v",
					len(got), len(want), got, want)
			}

			for i := range got {
				if got[i] != want[i] {
					t.Errorf("task %d differs:\n got %+v\nwant %+v", i, got[i], want[i])
				}
			}
		})
	}
}
