---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: docz
  title: Docz
  description: "A cli tool to help make managing repo docs easier."
  annotations:
    backstage.io/code-coverage: enabled
    backstage.io/source-location: url:https://github.com/donaldgifford/docz
    backstage.io/techdocs-ref: "dir:."
    github.com/project-slug: "donaldgifford/docz"
  tags:
    - go
    - github
  namespace: default
spec:
  owner: homelab
  type: tool
  system: dev-tools
  lifecycle: production
