nav:
    - Home: index.md
    - ADRs:
        - Overview: adr/README.md
    - Design:
        - Overview: design/README.md
        - 'DESIGN-0001: docz CLI Tool': design/0001-docz-cli-design.md
        - 'DESIGN-0002: Wiki Command for MkDocs TechDocs Integration': design/0002-wiki-command-for-mkdocs-techdocs-integration.md
        - 'DESIGN-0003: Table of Contents Generation': design/0003-table-of-contents-generation.md
    - Implementation Plans:
        - Overview: impl/README.md
        - 'IMPL-0001: docz CLI Implementation': impl/0001-docz-cli-implementation.md
        - 'IMPL-0002: Wiki Command for MkDocs TechDocs Integration': impl/0002-wiki-command-for-mkdocs-techdocs-integration.md
        - 'IMPL-0003: Table of Contents Generation': impl/0003-table-of-contents-generation.md
    - Investigations:
        - Overview: investigation/README.md
        - 'INV-0001: Wiki Init Template and Init Enabled Fix': investigation/0001-wiki-init-template-and-init-enabled-fix.md
    - Plans:
        - Overview: plan/README.md
    - RFCs:
        - Overview: rfc/README.md
plugins:
    - techdocs-core
site_description: Documentation for docz
site_name: docz
