package confluence

import (
	"bytes"
	"crypto/rand"
	"fmt"
	"io"
	"strings"

	"github.com/yuin/goldmark/util"

	"github.com/donaldgifford/docz/v2/pkg/doczcore/docparse"
)

// tocPlaceholder stands in for a ToC region's span until the renderer meets
// it as an HTML block.
const tocPlaceholder = "<!--docz-toc-->"

var (
	textEscaper = strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;")
	attrEscaper = strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;", "\n", " ")
)

// put and putf write to a page. Every writer they see is goldmark's buffer
// over the bytes.Buffer Render owns, or that buffer itself, and neither can
// fail, so there is no error to return.
func put(w io.Writer, s string) {
	_, _ = io.WriteString(w, s) //nolint:errcheck // writes to a bytes.Buffer cannot fail
}

func putf(w io.Writer, format string, args ...any) {
	_, _ = fmt.Fprintf(w, format, args...) //nolint:errcheck // writes to a bytes.Buffer cannot fail
}

// escapeText escapes s for an XML text node.
func escapeText(s string) string { return textEscaper.Replace(s) }

// escapeAttr escapes s for a double-quoted XML attribute.
func escapeAttr(s string) string { return attrEscaper.Replace(s) }

// codeLanguage maps a fence's info string to a code macro language:
// shell spellings to bash, yml to yaml, and anything the macro does not
// highlight to none.
func codeLanguage(lang string) string {
	switch lang {
	case "sh", "shell", "zsh", "console":
		return "bash"
	case "yml":
		return "yaml"
	case "js":
		return "javascript"
	case "py":
		return "python"
	}

	if knownLanguages[lang] {
		return lang
	}

	return "none"
}

// knownLanguages are the code macro languages docz passes through.
var knownLanguages = map[string]bool{
	"bash": true, "c": true, "cpp": true, "csharp": true, "css": true, "diff": true,
	"go": true, "groovy": true, "html": true, "java": true, "javascript": true,
	"json": true, "kotlin": true, "perl": true, "php": true, "powershell": true,
	"python": true, "ruby": true, "rust": true, "scala": true, "sql": true,
	"swift": true, "xml": true, "yaml": true,
}

// writeCode writes a code macro. A "]]>" in the body is split across two
// CDATA sections, the one sequence CDATA cannot hold.
func writeCode(w io.Writer, lang string, body []byte) {
	putf(w, `<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">%s</ac:parameter>`, lang)
	put(w, "<ac:plain-text-body><![CDATA[")
	put(w, string(bytes.ReplaceAll(body, []byte("]]>"), []byte("]]]]><![CDATA[>"))))
	put(w, "]]></ac:plain-text-body></ac:structured-macro>\n")
}

// writeExpand wraps what body writes in a collapsed expand macro.
func writeExpand(w io.Writer, title string, body func()) {
	putf(w, `<ac:structured-macro ac:name="expand"><ac:parameter ac:name="title">%s</ac:parameter><ac:rich-text-body>`,
		escapeText(title))
	body()
	put(w, "</ac:rich-text-body></ac:structured-macro>\n")
}

// writeTOC writes the toc macro.
func writeTOC(w io.Writer) {
	put(w, `<ac:structured-macro ac:name="toc"><ac:parameter ac:name="maxLevel">3</ac:parameter></ac:structured-macro>`+"\n")
}

// writeViewer writes the Mermaid diagrams viewer's Forge macro, in the
// storage form Confluence keeps for it (DESIGN-0020 §4). The viewer pairs
// the n-th macro with the n-th mermaid code block on the page.
func writeViewer(w util.BufWriter, key, localID string) {
	putf(w, `<ac:adf-extension><ac:adf-node type="extension">`+
		`<ac:adf-attribute key="extension-type">com.atlassian.ecosystem</ac:adf-attribute>`+
		`<ac:adf-attribute key="extension-key">%[1]s</ac:adf-attribute>`+
		`<ac:adf-attribute key="parameters">`+
		`<ac:adf-parameter key="local-id">%[2]s</ac:adf-parameter>`+
		`<ac:adf-parameter key="extension-id">ari:cloud:ecosystem::extension/%[1]s</ac:adf-parameter>`+
		`<ac:adf-parameter key="extension-title">Mermaid diagram</ac:adf-parameter>`+
		`</ac:adf-attribute>`+
		`<ac:adf-attribute key="text">Mermaid diagram</ac:adf-attribute>`+
		`<ac:adf-attribute key="layout">default</ac:adf-attribute>`+
		`<ac:adf-attribute key="local-id">%[2]s</ac:adf-attribute>`+
		`</ac:adf-node><ac:adf-fallback><p>Mermaid diagram</p></ac:adf-fallback></ac:adf-extension>`+"\n",
		escapeAttr(key), localID)
}

// writeBanner opens the page with an info panel naming the source and
// saying what becomes of an edit made in Confluence: kept until a forced
// sync, or, when overwrite is set, lost at the next sync.
func writeBanner(w io.Writer, source, sourceURL string, overwrite bool) {
	if source == "" {
		return
	}

	name := "<code>" + escapeText(source) + "</code>"
	if sourceURL != "" {
		name = `<a href="` + escapeAttr(sourceURL) + `">` + name + "</a>"
	}

	fate := "changes made here are kept until the next forced sync"
	if overwrite {
		fate = "changes made here are overwritten by the next sync"
	}

	putf(w, `<ac:structured-macro ac:name="info"><ac:rich-text-body><p>Generated by docz from %s. `+
		`Edit the markdown; %s.</p>`+
		"</ac:rich-text-body></ac:structured-macro>\n", name, fate)
}

// localIDPlaceholder is the stand-in for the n-th viewer macro's local id
// while the body is hashed, so the hash does not change from run to run.
func localIDPlaceholder(n int) string {
	return fmt.Sprintf("00000000-0000-4000-8000-%012d", n)
}

// mintLocalIDs replaces each of the n placeholders with a fresh UUID v4, so
// two macros on one page never share an id.
func mintLocalIDs(body []byte, n int) []byte {
	for i := range n {
		body = bytes.ReplaceAll(body, []byte(localIDPlaceholder(i)), []byte(newUUID()))
	}

	return body
}

// newUUID returns a random version 4 UUID.
func newUUID() string {
	var b [16]byte

	_, _ = rand.Read(b[:]) // crypto/rand.Read never fails (Go 1.24+)
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80

	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

// blankRegion replaces each region of kind with the ToC placeholder on its
// first line and blank lines for the rest, keeping the line count, so the
// span's generated body never reaches the page.
func blankRegion(body []byte, kind string) []byte {
	lines := bytes.SplitAfter(body, []byte("\n"))

	for _, r := range docparse.Regions(body) {
		if r.Kind != kind {
			continue
		}

		for i := r.Start; i <= r.End && i <= len(lines); i++ {
			lines[i-1] = []byte("\n")
		}

		lines[r.Start-1] = []byte(tocPlaceholder + "\n")
	}

	return bytes.Join(lines, nil)
}
