// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: confluence.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConfluenceSync = `-- name: GetConfluenceSync :one
SELECT repo_id, status, reason, site, space, folder_id, folder_title, folder_url, head_sha, counts, started_at, finished_at FROM confluence_syncs WHERE repo_id = $1
`

func (q *Queries) GetConfluenceSync(ctx context.Context, repoID int64) (ConfluenceSync, error) {
	row := q.db.QueryRow(ctx, getConfluenceSync, repoID)
	var i ConfluenceSync
	err := row.Scan(
		&i.RepoID,
		&i.Status,
		&i.Reason,
		&i.Site,
		&i.Space,
		&i.FolderID,
		&i.FolderTitle,
		&i.FolderUrl,
		&i.HeadSha,
		&i.Counts,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRepoByID = `-- name: GetRepoByID :one
SELECT id, installation_id, owner, name, default_branch, docs_dir, config_snapshot, last_synced_sha, last_synced_at, changelog_md, changelog_sha, created_at, updated_at, index_md, index_sha, changelog_file, api_landing_page, api_additional_docs FROM repos WHERE id = $1
`

func (q *Queries) GetRepoByID(ctx context.Context, id int64) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByID, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.Owner,
		&i.Name,
		&i.DefaultBranch,
		&i.DocsDir,
		&i.ConfigSnapshot,
		&i.LastSyncedSha,
		&i.LastSyncedAt,
		&i.ChangelogMd,
		&i.ChangelogSha,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IndexMd,
		&i.IndexSha,
		&i.ChangelogFile,
		&i.ApiLandingPage,
		&i.ApiAdditionalDocs,
	)
	return i, err
}

const listConfluencePageIDs = `-- name: ListConfluencePageIDs :many
SELECT key, page_id FROM confluence_pages WHERE repo_id = $1 AND page_id <> '' ORDER BY key
`

type ListConfluencePageIDsRow struct {
	Key    string `json:"key"`
	PageID string `json:"page_id"`
}

// Key to recorded page id, for ExportOptions.Pages.
func (q *Queries) ListConfluencePageIDs(ctx context.Context, repoID int64) ([]ListConfluencePageIDsRow, error) {
	rows, err := q.db.Query(ctx, listConfluencePageIDs, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConfluencePageIDsRow{}
	for rows.Next() {
		var i ListConfluencePageIDsRow
		if err := rows.Scan(&i.Key, &i.PageID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfluencePages = `-- name: ListConfluencePages :many
SELECT repo_id, key, doc_id, page_id, title, url, version, hash, action, reason, edited_from, comments_lost, synced_at FROM confluence_pages WHERE repo_id = $1 ORDER BY key
`

func (q *Queries) ListConfluencePages(ctx context.Context, repoID int64) ([]ConfluencePage, error) {
	rows, err := q.db.Query(ctx, listConfluencePages, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfluencePage{}
	for rows.Next() {
		var i ConfluencePage
		if err := rows.Scan(
			&i.RepoID,
			&i.Key,
			&i.DocID,
			&i.PageID,
			&i.Title,
			&i.Url,
			&i.Version,
			&i.Hash,
			&i.Action,
			&i.Reason,
			&i.EditedFrom,
			&i.CommentsLost,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsForExport = `-- name: ListDocumentsForExport :many
SELECT id, repo_id, type, doc_id, title, status, author, created, path, git_sha, content_hash, raw_md, updated_at FROM documents WHERE repo_id = $1 ORDER BY type, doc_id
`

// Every document with its markdown, for the export's file tree.
func (q *Queries) ListDocumentsForExport(ctx context.Context, repoID int64) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsForExport, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Type,
			&i.DocID,
			&i.Title,
			&i.Status,
			&i.Author,
			&i.Created,
			&i.Path,
			&i.GitSha,
			&i.ContentHash,
			&i.RawMd,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoPagesForExport = `-- name: ListRepoPagesForExport :many
SELECT id, repo_id, path, repo_path, title, git_sha, content_hash, raw_md, updated_at FROM repo_pages WHERE repo_id = $1 ORDER BY path
`

// Every published page with its markdown, for the export's file tree.
func (q *Queries) ListRepoPagesForExport(ctx context.Context, repoID int64) ([]RepoPage, error) {
	rows, err := q.db.Query(ctx, listRepoPagesForExport, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RepoPage{}
	for rows.Next() {
		var i RepoPage
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Path,
			&i.RepoPath,
			&i.Title,
			&i.GitSha,
			&i.ContentHash,
			&i.RawMd,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConfluencePage = `-- name: UpsertConfluencePage :exec
INSERT INTO confluence_pages (
    repo_id, key, doc_id, page_id, title, url, version, hash, action,
    reason, edited_from, comments_lost, synced_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (repo_id, key) DO UPDATE SET
    doc_id        = EXCLUDED.doc_id,
    page_id       = COALESCE(NULLIF(EXCLUDED.page_id, ''), confluence_pages.page_id),
    title         = EXCLUDED.title,
    url           = COALESCE(NULLIF(EXCLUDED.url, ''), confluence_pages.url),
    version       = EXCLUDED.version,
    hash          = EXCLUDED.hash,
    action        = EXCLUDED.action,
    reason        = EXCLUDED.reason,
    edited_from   = EXCLUDED.edited_from,
    comments_lost = EXCLUDED.comments_lost,
    synced_at     = EXCLUDED.synced_at
`

type UpsertConfluencePageParams struct {
	RepoID       int64              `json:"repo_id"`
	Key          string             `json:"key"`
	DocID        string             `json:"doc_id"`
	PageID       string             `json:"page_id"`
	Title        string             `json:"title"`
	Url          string             `json:"url"`
	Version      int32              `json:"version"`
	Hash         string             `json:"hash"`
	Action       string             `json:"action"`
	Reason       string             `json:"reason"`
	EditedFrom   int32              `json:"edited_from"`
	CommentsLost int32              `json:"comments_lost"`
	SyncedAt     pgtype.Timestamptz `json:"synced_at"`
}

// One page's result. A failed page passes an empty page_id and url, and
// keeps the previous row's, so a link that worked keeps working through a
// failed run (DESIGN-0021 Data Model).
func (q *Queries) UpsertConfluencePage(ctx context.Context, arg UpsertConfluencePageParams) error {
	_, err := q.db.Exec(ctx, upsertConfluencePage,
		arg.RepoID,
		arg.Key,
		arg.DocID,
		arg.PageID,
		arg.Title,
		arg.Url,
		arg.Version,
		arg.Hash,
		arg.Action,
		arg.Reason,
		arg.EditedFrom,
		arg.CommentsLost,
		arg.SyncedAt,
	)
	return err
}

const upsertConfluenceSync = `-- name: UpsertConfluenceSync :exec
INSERT INTO confluence_syncs (
    repo_id, status, reason, site, space, folder_id, folder_title, folder_url,
    head_sha, counts, started_at, finished_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (repo_id) DO UPDATE SET
    status       = EXCLUDED.status,
    reason       = EXCLUDED.reason,
    site         = EXCLUDED.site,
    space        = EXCLUDED.space,
    folder_id    = EXCLUDED.folder_id,
    folder_title = EXCLUDED.folder_title,
    folder_url   = EXCLUDED.folder_url,
    head_sha     = EXCLUDED.head_sha,
    counts       = EXCLUDED.counts,
    started_at   = EXCLUDED.started_at,
    finished_at  = EXCLUDED.finished_at
`

type UpsertConfluenceSyncParams struct {
	RepoID      int64              `json:"repo_id"`
	Status      string             `json:"status"`
	Reason      string             `json:"reason"`
	Site        string             `json:"site"`
	Space       string             `json:"space"`
	FolderID    string             `json:"folder_id"`
	FolderTitle string             `json:"folder_title"`
	FolderUrl   string             `json:"folder_url"`
	HeadSha     string             `json:"head_sha"`
	Counts      json.RawMessage    `json:"counts"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
}

// The repository's last export run, overwritten by each attempt
// (DESIGN-0021 §5 step 6).
func (q *Queries) UpsertConfluenceSync(ctx context.Context, arg UpsertConfluenceSyncParams) error {
	_, err := q.db.Exec(ctx, upsertConfluenceSync,
		arg.RepoID,
		arg.Status,
		arg.Reason,
		arg.Site,
		arg.Space,
		arg.FolderID,
		arg.FolderTitle,
		arg.FolderUrl,
		arg.HeadSha,
		arg.Counts,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}
