// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents WHERE repo_id = $1 AND doc_id = $2
`

type DeleteDocumentParams struct {
	RepoID int64  `json:"repo_id"`
	DocID  string `json:"doc_id"`
}

func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) error {
	_, err := q.db.Exec(ctx, deleteDocument, arg.RepoID, arg.DocID)
	return err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT d.id, d.repo_id, d.type, d.doc_id, d.title, d.status, d.author, d.created, d.path, d.git_sha, d.content_hash, d.raw_md, d.updated_at, COALESCE(cp.url, '')::text AS confluence_url
FROM documents d
LEFT JOIN confluence_pages cp ON cp.repo_id = d.repo_id AND cp.doc_id = d.doc_id
WHERE d.repo_id = $1 AND d.doc_id = $2
`

type GetDocumentByIDParams struct {
	RepoID int64  `json:"repo_id"`
	DocID  string `json:"doc_id"`
}

type GetDocumentByIDRow struct {
	Document      Document `json:"document"`
	ConfluenceUrl string   `json:"confluence_url"`
}

// Full row including raw_md for the single-doc endpoint, with the document's
// confluence_url as ListDocumentsByType reads it.
func (q *Queries) GetDocumentByID(ctx context.Context, arg GetDocumentByIDParams) (GetDocumentByIDRow, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, arg.RepoID, arg.DocID)
	var i GetDocumentByIDRow
	err := row.Scan(
		&i.Document.ID,
		&i.Document.RepoID,
		&i.Document.Type,
		&i.Document.DocID,
		&i.Document.Title,
		&i.Document.Status,
		&i.Document.Author,
		&i.Document.Created,
		&i.Document.Path,
		&i.Document.GitSha,
		&i.Document.ContentHash,
		&i.Document.RawMd,
		&i.Document.UpdatedAt,
		&i.ConfluenceUrl,
	)
	return i, err
}

const getDocumentsByIDs = `-- name: GetDocumentsByIDs :many
SELECT id, repo_id, type, doc_id, title, status, author, created, path, git_sha, content_hash, raw_md, updated_at FROM documents
WHERE repo_id = $1 AND doc_id = ANY($2::text[])
ORDER BY doc_id
`

type GetDocumentsByIDsParams struct {
	RepoID int64    `json:"repo_id"`
	DocIds []string `json:"doc_ids"`
}

// Full rows (including raw_md) for a set of doc ids in one repo; the search
// indexer uses this to build index documents after a reconcile commit.
func (q *Queries) GetDocumentsByIDs(ctx context.Context, arg GetDocumentsByIDsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, getDocumentsByIDs, arg.RepoID, arg.DocIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Type,
			&i.DocID,
			&i.Title,
			&i.Status,
			&i.Author,
			&i.Created,
			&i.Path,
			&i.GitSha,
			&i.ContentHash,
			&i.RawMd,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentHashes = `-- name: ListDocumentHashes :many
SELECT doc_id, content_hash FROM documents WHERE repo_id = $1
`

type ListDocumentHashesRow struct {
	DocID       string `json:"doc_id"`
	ContentHash string `json:"content_hash"`
}

func (q *Queries) ListDocumentHashes(ctx context.Context, repoID int64) ([]ListDocumentHashesRow, error) {
	rows, err := q.db.Query(ctx, listDocumentHashes, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentHashesRow{}
	for rows.Next() {
		var i ListDocumentHashesRow
		if err := rows.Scan(&i.DocID, &i.ContentHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByType = `-- name: ListDocumentsByType :many
SELECT d.id, d.repo_id, d.type, d.doc_id, d.title, d.status, d.author, d.created,
       d.path, d.git_sha, d.content_hash, d.updated_at,
       COALESCE(cp.url, '')::text AS confluence_url
FROM documents d
LEFT JOIN confluence_pages cp ON cp.repo_id = d.repo_id AND cp.doc_id = d.doc_id
WHERE d.repo_id = $1 AND d.type = $2
ORDER BY d.doc_id
`

type ListDocumentsByTypeParams struct {
	RepoID int64  `json:"repo_id"`
	Type   string `json:"type"`
}

type ListDocumentsByTypeRow struct {
	ID            int64              `json:"id"`
	RepoID        int64              `json:"repo_id"`
	Type          string             `json:"type"`
	DocID         string             `json:"doc_id"`
	Title         string             `json:"title"`
	Status        pgtype.Text        `json:"status"`
	Author        pgtype.Text        `json:"author"`
	Created       pgtype.Date        `json:"created"`
	Path          string             `json:"path"`
	GitSha        string             `json:"git_sha"`
	ContentHash   string             `json:"content_hash"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ConfluenceUrl string             `json:"confluence_url"`
}

// Metadata only (no raw_md) for the list endpoint; type is the canonical name.
// confluence_url is the page the last export wrote the document to, ” when
// there is none (DESIGN-0021 §7).
func (q *Queries) ListDocumentsByType(ctx context.Context, arg ListDocumentsByTypeParams) ([]ListDocumentsByTypeRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsByType, arg.RepoID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsByTypeRow{}
	for rows.Next() {
		var i ListDocumentsByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Type,
			&i.DocID,
			&i.Title,
			&i.Status,
			&i.Author,
			&i.Created,
			&i.Path,
			&i.GitSha,
			&i.ContentHash,
			&i.UpdatedAt,
			&i.ConfluenceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDocument = `-- name: UpsertDocument :exec
INSERT INTO documents (
    repo_id, type, doc_id, title, status, author, created,
    path, git_sha, content_hash, raw_md, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now()
)
ON CONFLICT (repo_id, doc_id) DO UPDATE SET
    type         = EXCLUDED.type,
    title        = EXCLUDED.title,
    status       = EXCLUDED.status,
    author       = EXCLUDED.author,
    created      = EXCLUDED.created,
    path         = EXCLUDED.path,
    git_sha      = EXCLUDED.git_sha,
    content_hash = EXCLUDED.content_hash,
    raw_md       = EXCLUDED.raw_md,
    updated_at   = now()
`

type UpsertDocumentParams struct {
	RepoID      int64       `json:"repo_id"`
	Type        string      `json:"type"`
	DocID       string      `json:"doc_id"`
	Title       string      `json:"title"`
	Status      pgtype.Text `json:"status"`
	Author      pgtype.Text `json:"author"`
	Created     pgtype.Date `json:"created"`
	Path        string      `json:"path"`
	GitSha      string      `json:"git_sha"`
	ContentHash string      `json:"content_hash"`
	RawMd       string      `json:"raw_md"`
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) error {
	_, err := q.db.Exec(ctx, upsertDocument,
		arg.RepoID,
		arg.Type,
		arg.DocID,
		arg.Title,
		arg.Status,
		arg.Author,
		arg.Created,
		arg.Path,
		arg.GitSha,
		arg.ContentHash,
		arg.RawMd,
	)
	return err
}
